// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhYGzTrAureNcnrp5ULa1yCkYOIUMc_Mc',
    appId: '1:321481713488:web:49d9ecbffe2f341fb92e55',
    messagingSenderId: '321481713488',
    projectId: 'eye-solution-challenge',
    authDomain: 'eye-solution-challenge.firebaseapp.com',
    storageBucket: 'eye-solution-challenge.appspot.com',
    measurementId: 'G-MBYQW0JYE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1NwkB9dVMtSsP--AJwrxRPkoQlRbI92g',
    appId: '1:321481713488:android:0334f355bce098ebb92e55',
    messagingSenderId: '321481713488',
    projectId: 'eye-solution-challenge',
    storageBucket: 'eye-solution-challenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE-ngYIL58iqBP4FcHEkXlAr17wQ-uKo0',
    appId: '1:321481713488:ios:47677e18c38ef21fb92e55',
    messagingSenderId: '321481713488',
    projectId: 'eye-solution-challenge',
    storageBucket: 'eye-solution-challenge.appspot.com',
    iosClientId: '321481713488-i9p3egb1c36vegtk0kejf0vivmffu6ru.apps.googleusercontent.com',
    iosBundleId: 'com.example.eye',
  );
}
